"""Criacao de todas as tabelas

Revision ID: e63430140749
Revises: 1663a5121b3d
Create Date: 2024-12-16 10:57:35.212877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63430140749'
down_revision = '1663a5121b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_popular', sa.String(length=255), nullable=True),
    sa.Column('nome_cientifico', sa.String(length=255), nullable=True),
    sa.Column('familia', sa.String(length=255), nullable=True),
    sa.Column('origem', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('ciclo_vida', sa.String(length=400), nullable=True),
    sa.Column('crescimento', sa.String(length=500), nullable=True),
    sa.Column('quando_fruto', sa.String(length=255), nullable=True),
    sa.Column('quando_flores', sa.String(length=255), nullable=True),
    sa.Column('flores', sa.String(length=700), nullable=True),
    sa.Column('clima_nativo', sa.String(length=200), nullable=True),
    sa.Column('clima_permitido', sa.String(length=200), nullable=True),
    sa.Column('adubacao', sa.String(length=1200), nullable=True),
    sa.Column('como_regar', sa.String(length=1000), nullable=True),
    sa.Column('aceita_poda', sa.Integer(), nullable=True),
    sa.Column('sombra', sa.String(length=255), nullable=True),
    sa.Column('altura_muda', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('logradouro', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=50), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('categoria_planta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['planta_id'], ['planta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interesse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['planta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('publicacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('caminho', sa.String(length=120), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('publicacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('publicacao_id', sa.Integer(), nullable=False),
    sa.Column('interesse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interesse_id'], ['interesse.id'], ),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('notificacao')
    op.drop_table('foto')
    op.drop_table('contactar')
    op.drop_table('publicacao')
    op.drop_table('interesse')
    op.drop_table('categoria_planta')
    op.drop_table('usuario')
    op.drop_table('planta')
    op.drop_table('categoria')
    # ### end Alembic commands ###
